font_sources:
  - name: google_fonts
    type: api
    url: https://www.googleapis.com/webfonts/v1/webfonts
    api_key: AIzaSyCSvL4yB61uFOu_V6pjItmkCs0d6zSfuKg

output_dir: data/fonts
img_size: 16
font_size: 18 # 18pt text in a 16x16 image works fairly well
min_chars_required: 48
index_file: index.json # In output_dir