font_sources:
  - name: google_fonts
    type: api
    url: https://www.googleapis.com/webfonts/v1/webfonts
    api_key: YOUR_API_KEY

output_dir: data/fonts
img_size: 32
font_size: 28 # 28pt text in a 32x32 image works fairly well
min_chars_required: 48
index_file: index.json # In output_dir